# Generated by Django 5.0.6 on 2024-07-08 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="record",
            name="first_name",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
